const QUESTS = {
  q_zelador: {
    npc:'Zelador', titulo:'Rastros sob a Pedra',
    tipo:'hunt', alvo:'wolf', qtd:6,
    resumo:'Derrotar 6 Lobos de Éter no Subterrâneo.',
    oferta:['Desde que reforçaram as cercas, os lobos não chegam mais ao pátio.',
            'Mas as pegadas descem pela escada selada. Tire seis de lá e eu pago do meu bolso. Topa?'],
    andamento:['Os rastros ainda descem. Volte depois de tirar seis lobos da passagem.'],
    entrega:['Seis? Você contou mesmo. Gosto disso.',
             'Agora eles ficam lá embaixo. E não conta pra diretora que eu paguei aluno pra trabalhar.'],
    depois:['O pátio está quieto. Do jeito que devia ser.'],
    premio:{gold:450, itens:['potion','potion','antidote']},
    cena:'entrega_zelador',
  },
  q_enfermeira: {
    npc:'Enfermeira', titulo:'Reserva da Enfermaria',
    tipo:'collect', item:'ether', qtd:4,
    resumo:'Entregar 4 Elixires de Éter à enfermeira.',
    oferta:['A reserva de éter acabou e a academia não repõe.',
            'Me traga quatro elixires e eu te devolvo em algo melhor.'],
    andamento:['Quatro elixires. Não é pedido difícil, é pedido chato.'],
    entrega:['Isso resolve o mês. Obrigada.',
             'Fiz o que dava com o que sobrou. Leve.'],
    depois:['A reserva está de pé. Por enquanto.'],
    premio:{gold:200, itens:['hipot','hipot','hiether']},
  },
  q_veterano: {
    npc:'Veterano', titulo:'Prova de Pedra',
    tipo:'hunt', alvo:'golem', qtd:3,
    resumo:'Abater 3 Golems de Pedra no subterrâneo.',
    oferta:['Quer saber se aprendeu o anel? Golem não tem elemento.',
            'Contra ele não existe atalho: só dano e paciência. Derrube três.'],
    andamento:['Três golems. Sem elemento pra te salvar. Volte quando souber.'],
    entrega:['Então você aprendeu a bater sem muleta. Bom.',
             'Isso aqui era do meu grupo. Não sobrou mais ninguém pra usar.'],
    depois:['Bata primeiro em quem é fraco ao que você tem. Sempre.'],
    premio:{gold:600, itens:['w_treino','a_manto']},
  },
  q_bibliotecaria: {
    npc:'Bibliotecária', titulo:'O Que Não Se Anota',
    tipo:'hunt', alvo:'shade', qtd:5,
    resumo:'Abater 5 Sombras Corrompidas.',
    oferta:['As sombras estão subindo. Eu não posso registrar isso em lugar nenhum.',
            'Cinco. Se você reduzir a cinco, eu finjo que nunca contei.'],
    andamento:['Cinco sombras. E não escreva isso em lugar nenhum.'],
    entrega:['Obrigada. Oficialmente, esta conversa não aconteceu.',
             'Estava numa gaveta que oficialmente também não existe.'],
    depois:['O salão está mais quieto. Não pergunte por quê.'],
    premio:{gold:500, itens:['t_foco','ether','ether']},
  },
  q_mercador: {
    npc:'Mercador Errante', titulo:'Estoque Difícil',
    tipo:'hunt', alvo:'sentinel', qtd:4,
    resumo:'Abater 4 Sentinelas de Luz na Galeria.',
    oferta:['Sentinela carrega um núcleo que eu revendo muito bem.',
            'Quatro núcleos e eu abro a gaveta de baixo pra você.'],
    andamento:['Quatro sentinelas. Núcleo inteiro, de preferência.'],
    entrega:['Negócio é negócio. A gaveta de baixo é sua.',
             'Não pergunte de onde veio. Você também não perguntou de mim.'],
    depois:['A gaveta de baixo continua aberta pra você.'],
    premio:{gold:1500, itens:['megapot','phoenix','t_agil']},
  },

  /* ================= v4.8: MISSÕES DO PÓS-JOGO =====================
     Doze missões nas três regiões novas. Nenhuma delas traz gente para
     o elenco (`RECRUIT_QUESTS` continua com as cinco originais): aqui o
     prêmio é EQUIPAMENTO — e cada uma entrega justamente a peça que
     resolve a região seguinte. É o mesmo contrato do Selo Ressonante,
     esticado para o resto do jogo. ================================== */

  // --- Mata Cindária ---
  q_batedora: {
    npc:'Batedora', titulo:'Trilha de Cinzas',
    tipo:'hunt', alvo:'ashwolf', qtd:8,
    resumo:'Abater 8 Lobos de Cinzas na Mata Cindária.',
    oferta:['A trilha era minha. Agora é dos lobos, e eles não pagam pedágio.',
            'Oito. Depois disso eu volto a andar por aqui de cabeça erguida.'],
    andamento:['Ainda tem lobo demais entre mim e o acampamento.'],
    entrega:['Oito. Eu contei os uivos que pararam.',
             'Fica com isso. Onde eu vou, roupa de cinza não ajuda mais.'],
    depois:['A trilha é minha de novo. Obrigada.'],
    premio:{gold:2200, itens:['a_casco','medkit','medkit']},
    cena:'entrega_batedora',
  },
  q_lenhador: {
    npc:'Lenhador', titulo:'Lenha Que Não Queima',
    tipo:'hunt', alvo:'charwood', qtd:5,
    resumo:'Derrubar 5 Troncos Queimados.',
    oferta:['Eu corto lenha há trinta anos. Nunca vi tronco que corta de volta.',
            'Cinco. Não peço mais que isso porque cinco já é loucura.'],
    andamento:['Cinco troncos. E não vale contar os que já estavam caídos.'],
    entrega:['Então é verdade que dá pra derrubar. Bom saber antes de morrer.',
             'Peguei isso de um que já não precisava mais.'],
    depois:['A clareira tá quase decente. Quase.'],
    premio:{gold:2600, itens:['w_carvao','hipot','hipot']},
  },
  q_guardafogo: {
    npc:'Guarda-Fogo', titulo:'Brasas Soltas',
    tipo:'hunt', alvo:'emberling', qtd:10,
    resumo:'Apagar 10 Brasas Errantes.',
    oferta:['Cada brasa dessas é um incêndio que ainda não decidiu acontecer.',
            'Dez. Apague dez e eu durmo esta noite.'],
    andamento:['Dez brasas. Eu conto pela fumaça, então não adianta mentir.'],
    entrega:['Dez. O ar mudou de cheiro. Você sente?',
             'Leve. Serve pra quem anda onde eu não ando mais.'],
    depois:['Enquanto tiver mata, vai ter brasa. Mas hoje não.'],
    premio:{gold:1800, itens:['t_brasa','ironspike'], pet:'coelho'},
  },
  q_alquimista: {
    npc:'Alquimista', titulo:'Encomenda de Frascos',
    tipo:'collect', item:'bomb', qtd:4,
    resumo:'Entregar 4 Frascos Ígneos ao alquimista do acampamento.',
    oferta:['Eu sei fazer frasco. O que eu não sei é sair daqui pra buscar material.',
            'Quatro Frascos Ígneos e eu te devolvo em coisa melhor. Palavra de comerciante honesto.'],
    andamento:['Quatro frascos. Íntegros, de preferência.'],
    entrega:['Perfeito. Nenhum trincado. Você tem mão boa.',
             'Isto aqui eu guardava pra mim. Guardar não estava rendendo.'],
    depois:['Volte quando tiver mais. Eu sempre compro.'],
    premio:{gold:1500, itens:['bigbomb','warcry','aegis']},
  },

  // --- Cisterna Afogada ---
  q_comporta: {
    npc:'Engenheira', titulo:'Ferrugem na Comporta',
    tipo:'hunt', alvo:'sluicewarden', qtd:5,
    resumo:'Destruir 5 Guardas da Comporta.',
    oferta:['A comporta não enferrujou sozinha. Tem coisa cuidando dela.',
            'Cinco guardas. Sem eles eu consigo ler o mecanismo.'],
    andamento:['Cinco. Enquanto eles estiverem de pé eu não chego perto.'],
    entrega:['Consegui ler o mecanismo. E não gostei do que estava escrito.',
             'Pegue a escama. Ela segura o frio dessa água melhor que qualquer manta.'],
    depois:['A comporta continua fechada. Mas agora eu sei por quê.'],
    premio:{gold:4000, itens:['a_escama','hiether','hiether']},
    cena:'entrega_comporta',
  },
  q_contagem: {
    npc:'Escriturário', titulo:'Contagem dos Afogados',
    tipo:'hunt', alvo:'drowned', qtd:9,
    resumo:'Abater 9 Afogados na Cisterna.',
    oferta:['Alguém tem que contar. Se ninguém contar, é como se não tivessem existido.',
            'Nove. Eu tenho nove nomes numa lista e nenhum corpo em paz.'],
    andamento:['Nove nomes. Ainda faltam alguns.'],
    entrega:['Nove. Está fechado. Obrigado — de verdade.',
             'Isto estava com o sexto da lista. Ele não vai reclamar.'],
    depois:['A lista está fechada. É tudo que eu queria.'],
    premio:{gold:3400, itens:['w_mare','panacea','panacea']},
  },
  q_canto: {
    npc:'Mergulhador', titulo:'Silenciar o Canto',
    tipo:'hunt', alvo:'siren', qtd:5,
    resumo:'Calar 5 Cantoras Submersas.',
    oferta:['O canto entra pelo ouvido e sai pelas pernas. Eu já vi gente andar pra dentro da água sorrindo.',
            'Cinco. Cale cinco e eu volto a mergulhar.'],
    andamento:['Cinco cantoras. E não escute enquanto trabalha.'],
    entrega:['Silêncio. Eu tinha esquecido como era.',
             'Achei isso no fundo, no primeiro mergulho depois que você limpou.'],
    depois:['A água tá quieta. Quieta demais, mas quieta.'],
    premio:{gold:4200, itens:['t_sino','hiether'], pet:'corvo'},
  },
  q_aguaeter: {
    npc:'Enfermeira de Campo', titulo:'Água Que Guarda Éter',
    tipo:'collect', item:'hiether', qtd:3,
    resumo:'Entregar 3 Éteres Destilados à enfermeira de campo.',
    oferta:['Aqui embaixo o éter não circula. Quem cai, cai duas vezes.',
            'Três destilados. Com três eu monto um posto que presta.'],
    andamento:['Três destilados. Não é pedido difícil — é pedido caro.'],
    entrega:['Com isso eu atendo até a comporta abrir.',
             'Leve a cinza. Se você cair aí dentro, alguém precisa levantar o resto.'],
    depois:['O posto está de pé. Enquanto durar.'],
    premio:{gold:2800, itens:['rebirth','dew','dew']},
  },

  // --- Coroa de Vidro ---
  q_cacos: {
    npc:'Vidraceiro', titulo:'Cacos de Vidro',
    tipo:'hunt', alvo:'glasswing', qtd:8,
    resumo:'Abater 8 Asas de Vidro na Coroa.',
    oferta:['Cada uma dessas leva um caco quando voa. A torre está se desmontando aos poucos.',
            'Oito asas. Oito cacos de volta ao lugar.'],
    andamento:['Oito. Eu ouço quando uma passa — ainda passa demais.'],
    entrega:['A torre parou de tilintar. Nunca pensei que fosse sentir falta do barulho.',
             'Feito com o que você trouxe. Ela devolve luz.'],
    depois:['O vidro está inteiro. Por ora.'],
    premio:{gold:7000, itens:['t_espelho','nectar']},
  },
  q_reflexo: {
    npc:'Astrônoma', titulo:'O Que o Espelho Devolve',
    tipo:'hunt', alvo:'crackmirror', qtd:6,
    resumo:'Quebrar 6 Reflexos Rachados.',
    oferta:['Eu vim medir estrelas e passei a ser medida por elas.',
            'Seis reflexos. Enquanto eles existirem, eu não sei qual leitura é minha.'],
    andamento:['Seis. Cada um que sobra escreve uma linha diferente no meu caderno.'],
    entrega:['Agora o caderno tem uma leitura só. É a minha.',
             'Isto estava no observatório antes de mim. Serve melhor em você.'],
    depois:['Uma leitura só. É tudo que um astrônomo quer.'],
    premio:{gold:8000, itens:['w_aurora','nectar']},
  },
  q_vazio: {
    npc:'Eremita', titulo:'Filhos do Vazio',
    tipo:'hunt', alvo:'voidling', qtd:7,
    resumo:'Dispersar 7 Crias do Vazio.',
    oferta:['Eles não querem nada. É o que os torna insuportáveis.',
            'Sete. Disperse sete e eu volto a meditar sem companhia.'],
    andamento:['Sete crias. Elas não fogem — só não acabam.'],
    entrega:['Silêncio de verdade. Não o silêncio delas, o meu.',
             'Fique com o martelo. Eu já quebrei tudo que precisava quebrar.'],
    depois:['O vazio continua. Só não tem mais filhos aqui.'],
    premio:{gold:7500, itens:['t_martelo','rebirth'], pet:'sapo'},
  },
  q_antescoroa: {
    npc:'Último Arauto', titulo:'Antes da Coroa',
    tipo:'hunt', alvo:'lesserherald', qtd:5,
    resumo:'Derrotar 5 Arautos Menores antes de enfrentar a Coroa.',
    oferta:['Eu fui o primeiro a anunciá-la. Passei o resto do tempo tentando desanunciar.',
            'Cinco arautos. Cada um que cala é uma trombeta a menos quando você subir.'],
    andamento:['Cinco. Enquanto tocarem, ela sabe que você está vindo.'],
    entrega:['Ela não sabe mais que você vem. É a única vantagem que existe aqui.',
             'Leve o paramento. Eu não vou precisar dele para o que vem depois.'],
    depois:['Suba quando estiver pronto. Ela não vai a lugar nenhum.'],
    premio:{gold:12000, itens:['a_astral','nectar','rebirth']},
    cena:'entrega_arauto',
  },

  /* ================= v4.9: NINHAL DE ÉTER ==========================
     Sete missões, e a diferença em relação à rodada passada é o TIPO:
     cinco são de COLETA de material que cai da criatura, não "mate N".
     A distinção importa mais do que parece — caçada é um contador que
     só sobe, coleta depende de sorte no drop e faz o jogador olhar a
     bolsa, vender ou guardar. É a mesma tarefa com outra textura.

     O prêmio destas é `pet`: cada uma entrega um bicho. É por isso que
     a região existe. ================================================ */

  q_plumas: {
    npc:'Tratadora', titulo:'O Que o Vento Deixou',
    tipo:'collect', item:'m_pluma', qtd:8,
    resumo:'Juntar 8 Plumas de Éter das crias do Ninhal.',
    oferta:['Pluma de Éter não cai no chão. Fica parada no ar esperando alguém pegar.',
            'Junte oito e eu te apresento uma que já aprendeu a voltar sozinha.'],
    andamento:['Oito plumas. Elas ficam paradas no ar — é só ter paciência.'],
    entrega:['Oito. E nenhuma amassada, o que diz mais de você do que da pluma.',
             'Essa aqui escolheu você antes de eu terminar de falar. Leve.'],
    depois:['Ela volta sempre. É o defeito e a graça da raça.'],
    premio:{gold:1800, itens:['p_racao','p_racao'], pet:'falcao'},
  },
  q_casulos: {
    npc:'Parteira de Ninho', titulo:'Casulos Mornos',
    tipo:'collect', item:'m_casulo', qtd:5,
    resumo:'Recolher 5 Casulos Mornos no Ninhal.',
    oferta:['Casulo morno é casulo com alguém dentro. Casulo frio eu já não pego.',
            'Cinco mornos. Cinco chances de alguma coisa dar certo.'],
    andamento:['Cinco casulos. E MORNOS — se estiver frio, deixe onde está.'],
    entrega:['Quatro não vingaram. Um vingou. É a média boa, acredite.',
             'Ela não corre de nada. Só chega antes. Vai entender com o tempo.'],
    depois:['Um em cinco. Todo ano é assim e todo ano eu me surpreendo.'],
    premio:{gold:2400, itens:['p_bolo'], pet:'homunculo'},
  },
  q_presas: {
    npc:'Caçador de Ninho', titulo:'Presas Que Ainda Aquecem',
    tipo:'collect', item:'m_presa', qtd:6,
    resumo:'Trazer 6 Presas Cindárias.',
    oferta:['Presa de cornuda esfria em uma hora. Depois disso não serve pra nada.',
            'Seis quentes. Se chegarem frias eu não pago, e não é birra: é que não serve.'],
    andamento:['Seis presas, e rápido. Frias não valem.'],
    entrega:['Todas mornas. Você correu de verdade.',
             'Isto aqui dormia no meu tinteiro. Acorda quando a página pega fogo.'],
    depois:['Enquanto tiver cornuda na mata, tem presa. E tem trabalho.'],
    premio:{gold:2200, itens:['p_racao','bomb'], pet:'polvo'},
  },
  q_escamas: {
    npc:'Ferreiro do Ninhal', titulo:'Placa Sobre Placa',
    tipo:'collect', item:'m_escama', qtd:6,
    resumo:'Entregar 6 Escamas Afogadas ao ferreiro.',
    oferta:['Escama de cascudo é a única placa que eu conheço que fica mais dura depois de molhada.',
            'Seis e eu monto uma armadura. Ou um amigo. Depende do humor.'],
    andamento:['Seis escamas. De cascudo, não de peixe — dá pra ver a diferença.'],
    entrega:['Deu pra armadura E pro amigo. Dia bom.',
             'Ele anda de lado na direção exata do problema. Nunca vi errar.'],
    depois:['A bigorna tá quente. Traga mais escama quando tiver.'],
    premio:{gold:2600, itens:['a_bruma'], pet:'salamandra'},
  },
  q_ladroes: {
    npc:'Vigia do Ninhal', titulo:'Quem Anda Entre os Ovos',
    tipo:'hunt', alvo:'ladraninho', qtd:7,
    resumo:'Abater 7 Ladrões de Ovos.',
    oferta:['Eu vigio o ninhal há nove anos. Sei a diferença entre bicho com fome e bicho com plano.',
            'Sete. Os que têm plano.'],
    andamento:['Sete ladrões. Os outros bichos podem ficar.'],
    entrega:['Sete. Hoje eu durmo.',
             'Esse aí aparece atrás de quem você estava olhando. Combina com quem trabalha à noite.'],
    depois:['Enquanto tiver ovo, vai ter ladrão. Mas hoje não.'],
    premio:{gold:2800, itens:['p_bolo'], pet:'morcego'},
  },
  q_cornudas: {
    npc:'Pastor de Cria', titulo:'A Que Não Volta',
    tipo:'hunt', alvo:'cornuda', qtd:5,
    resumo:'Derrubar 5 Cornudas Cindárias.',
    oferta:['Cornuda entra no ninhal pra comer cria. Não é maldade dela, mas também não é problema meu.',
            'Cinco. Depois disso as outras aprendem e desviam.'],
    andamento:['Cinco cornudas. Elas contam melhor que a gente.'],
    entrega:['As outras já estão desviando. Elas aprendem rápido quando o preço aparece.',
             'Isso aqui morreu uma vez e não achou que fosse motivo pra parar. Serve pra você?'],
    depois:['O ninhal tá mais quieto. Aproveite enquanto dura.'],
    premio:{gold:3000, itens:['p_bolo','megapot'], pet:'lince'},
  },
  /* A única que não dá para terminar aqui: o Caco Cantante só cai na
     Coroa de Vidro. É o jeito de deixar o dragão para o fim do jogo sem
     precisar de flag — o material é a fechadura. */
  q_dragao: {
    npc:'Guardiã de Ninho', titulo:'O Que a Diretora Deixou',
    tipo:'collect', item:'m_caco', qtd:5,
    resumo:'Levar 5 Cacos Cantantes à guardiã do Ninhal.',
    oferta:['Tem um ovo aqui que não é daqui. Foi a diretora Felt que trouxe, e ela não explicou.',
            'Ele só responde a vidro que canta. Cinco cacos da Coroa e a gente descobre o que tem dentro.'],
    andamento:['Cinco cacos, e só os da Coroa cantam. Os outros são caco e pronto.'],
    entrega:['Ele acordou no terceiro caco. No quinto já tinha decidido que a casa é sua.',
             'A Felt vai saber. Ela sempre sabe. Se ela quiser de volta, o problema é entre vocês.'],
    depois:['Ela nunca disse por que deixou de ser dela. Eu também nunca perguntei.'],
    premio:{gold:9000, itens:['p_banquete','p_banquete'], pet:'dragao'},
  },
  /* --- Arquivo Esquecido (v5.24) ---------------------------------- */
  q_arquivo_indice: {
    npc:'Arquivista Aposentado', titulo:'O Acervo Se Mexe',
    tipo:'hunt', alvo:'indice', qtd:8,
    resumo:'Abater 8 Índices Vivos no Arquivo Esquecido.',
    oferta:['Um índice é uma lista de onde as coisas estão. Estes aqui esqueceram onde estavam.',
            'Enquanto andam soltos, nada neste acervo fica no lugar. Derrube oito.'],
    andamento:['Ainda tem índice andando. Eu ouço as fichas trocando de gaveta.'],
    entrega:['Oito. O acervo parou de se mexer por um instante.',
             'Fique com isto. Estava catalogado como "sem dono", e é verdade.'],
    depois:['Cataloguei você. Nome, procedência, data de entrada. Agora você consta.'],
    premio:{gold:2600, itens:['hiether','hiether','t_marcador']},
  },
  q_arquivo_lacre: {
    npc:'Copista', titulo:'Lacre Rompido',
    tipo:'collect', item:'m_lacre', qtd:5,
    resumo:'Entregar 5 Lacres Rompidos ao copista.',
    oferta:['Todo volume selado aqui foi aberto POR DENTRO. Isso me tira o sono.',
            'Traga cinco lacres. Quero comparar a cera — se for a mesma mão, eu paro de copiar.'],
    andamento:['Cinco lacres. Rompidos, não cortados. A diferença é tudo.'],
    entrega:['A mesma cera. A mesma mão. Em volumes de séculos diferentes.',
             'Leve isto e vá embora antes de eu terminar de pensar no que isso quer dizer.'],
    depois:['Continuo copiando. Agora é teimosia, não trabalho.'],
    premio:{gold:3200, itens:['nectar','a_encader']},
  },
  /* Esta missão existe por causa do sistema de ECO (v5.24): sem um
     motivo escrito, o rematch fica sendo uma opção que ninguém aperta
     duas vezes. Ela conta abates de chefe, que é o que `G.kills` já
     registra — inclusive nas revanches. */
  q_ecos: {
    npc:'Mercadora de Margem', titulo:'Três Ecos',
    tipo:'hunt', alvo:'swampking', qtd:3,
    resumo:'Derrubar 3 vezes o eco do Dono do Pântano, na Comporta.',
    oferta:['Coisa grande que morre aqui não some: fica ecoando no lugar onde caiu.',
            'O da comporta ainda ronda. Derrube o eco três vezes e eu te pago pelo que solta.'],
    andamento:['Três vezes. Ele endurece a cada uma — é esse o preço.'],
    entrega:['Três. Você não devia conseguir isso e conseguiu.',
             'Isto aqui eu guardava para mim. Guarde você.'],
    depois:['Eco derrubado demais para de voltar inteiro. O seu já está pela metade.'],
    premio:{gold:5000, itens:['nectar','rebirth','w_verbete']},
  },

  /* ================= v5.28: MISSÕES DAS QUATRO REGIÕES ==============
     Duas por região: uma CAÇADA e uma COLETA. A caçada mira a espécie
     que dá nome à região, a coleta usa o material que só cai ali. As
     quantidades saíram medidas, não escolhidas: `assertQuestsCompletáveis`
     reprova acima de 15 encontros, e a primeira versão do Esgoto pedia
     9 válvulas com o Coletor saindo em duas formações de oito.

     Prêmio é equipamento da faixa SEGUINTE, como nas outras: missão que
     paga o que a região já dá é troféu, não preparação. ============= */

  // --- Galerias de Esgoto ---
  q_valvulas: {
    npc:'Encanador Aposentado', titulo:'O Que Ficou Girando',
    tipo:'collect', item:'m_valvula', qtd:6,
    resumo:'Recolher 6 Válvulas Enferrujadas nas galerias.',
    oferta:['Cada bicho daqui engoliu uma peça da minha galeria. Não foi por fome.',
            'Seis válvulas. Com seis eu fecho o ramal e durmo uma noite inteira.'],
    andamento:['Seis. Enferrujadas serve. Engolidas também.'],
    entrega:['Seis. O ramal fecha hoje.',
             'Leva isso. Era do rapaz que desceu antes de você e não subiu.'],
    depois:['O ramal está fechado. A água desce onde tem que descer.'],
    premio:{gold:900, itens:['a_manto','panacea','hipot']},
  },
  q_coletores: {
    npc:'Cobradora de Fossa', titulo:'Metro de Galeria Limpa',
    tipo:'hunt', alvo:'coletor', qtd:5,
    resumo:'Abater 5 Coletores Mutantes no esgoto.',
    oferta:['A Academia paga por metro limpo. O problema é o que mora no metro.',
            'Cinco coletores. Cinco, e eu consigo medir o resto sem correr.'],
    andamento:['Cinco coletores. Eu conto pela quantidade de cano que volta a passar água.'],
    entrega:['Cinco. Já dá para medir a galeria inteira.',
             'A Academia paga em dinheiro. Eu pago nisto, que é melhor.'],
    depois:['Dá para andar a galeria inteira agora. Obrigada.'],
    premio:{gold:1100, itens:['t_vital','w_volt']},
  },

  // --- Lago Afogado ---
  q_juncos: {
    npc:'Pescadora Sem Rede', titulo:'O Verde Por Fora',
    tipo:'collect', item:'m_junco', qtd:7,
    resumo:'Recolher 7 Juncos Afogados no lago.',
    oferta:['Junco daqui é verde por fora e preto por dentro. Serve para amarrar o que não quer ficar.',
            'Sete. Com sete eu remendo a rede e volto a pescar peixe, não gente.'],
    andamento:['Sete juncos. Os que vêm com o bicho junto valem igual.'],
    entrega:['Sete. A rede volta a ser rede.',
             'Isto veio do fundo, num dia em que eu ainda descia.'],
    depois:['Peguei três peixes ontem. PEIXES. Faz anos.'],
    premio:{gold:1600, itens:['a_bruma','t_corda']},
  },
  q_serpente: {
    npc:'Barqueiro', titulo:'Travessia Sem Fome',
    tipo:'hunt', alvo:'serpente_lago', qtd:4,
    resumo:'Abater 4 Serpentes Lacustres.',
    oferta:['Eu atravesso quem paga. Voltar é a parte que a serpente decide.',
            'Quatro. Quatro e eu volto a cobrar preço de barqueiro, não de aposta.'],
    andamento:['Quatro serpentes. Conto pelas viagens que eu faço sem olhar para trás.'],
    entrega:['Quatro. Hoje eu atravessei de olhos fechados.',
             'Isto estava no fundo do barco desde antes de mim.'],
    depois:['A travessia é só travessia agora. É o máximo que se pede de um lago.'],
    premio:{gold:2000, itens:['w_mare','megapot','megapot']},
  },

  // --- Baixios da Podridão ---
  q_esporos: {
    npc:'Coveiro de Turfa', titulo:'O Que Sobe de Novo',
    tipo:'collect', item:'m_esporo', qtd:8,
    resumo:'Recolher 8 Esporos Podres nos baixios.',
    oferta:['Cavo raso porque o fundo não segura. Em três dias sobe tudo outra vez.',
            'Oito esporos. Queimados juntos, seguram a terra por uma estação.'],
    andamento:['Oito. Não aperte no caminho — eles explodem em pó.'],
    entrega:['Oito. Vou queimar hoje à noite, com o vento a favor.',
             'Isto eu tirei de uma cova que não era para ser aberta.'],
    depois:['A terra está segurando. Primeira vez em três anos.'],
    premio:{gold:2400, itens:['a_casco','panacea','panacea']},
  },
  q_carnicais: {
    npc:'Herbolária Amarga', titulo:'Escolher Qual',
    tipo:'hunt', alvo:'carnical', qtd:6,
    resumo:'Abater 6 Carniçais Putrefactos.',
    oferta:['Tudo que cresce aqui cura uma coisa e mata outra. O ofício é escolher qual.',
            'Os carniçais escolhem por mim, e escolhem errado. Seis deles.'],
    andamento:['Seis carniçais. Depois disso eu volto a colher onde quero.'],
    entrega:['Seis. O canteiro do leste é meu de novo.',
             'Beba se precisar. Não beba se não precisar. Vale para tudo aqui.'],
    depois:['O canteiro do leste está limpo. O do norte, ainda não.'],
    premio:{gold:2800, itens:['t_brasa','w_carvao']},
  },

  // --- Deserto de Vidro Moído ---
  q_carapacas: {
    npc:'Cartógrafa de Areia', titulo:'O Mapa Que a Areia Desmente',
    tipo:'collect', item:'m_carapaca', qtd:6,
    resumo:'Recolher 6 Carapaças Solares no deserto.',
    oferta:['Desenho o deserto toda manhã. Toda tarde ele desmente o desenho.',
            'Carapaça de escaravelho guarda calor. Seis delas seguram uma bússola parada.'],
    andamento:['Seis carapaças. As mornas servem melhor.'],
    entrega:['Seis. A bússola parou de girar. Pela primeira vez o mapa vai durar.',
             'Fique com isto. Onde eu vou, peso é inimigo.'],
    depois:['O mapa de hoje ainda vale amanhã. Você não sabe o que isso significa aqui.'],
    premio:{gold:5200, itens:['t_olho','nectar','elixir']},
  },
  q_mumias: {
    npc:'Caravaneiro Cego', titulo:'Quem Anda Sem Rumo',
    tipo:'hunt', alvo:'mumia', qtd:5,
    resumo:'Abater 5 Múmias Errantes.',
    oferta:['Não preciso enxergar. Aqui tudo tem a mesma cor de qualquer jeito.',
            'Mas eu ouço as que andam sem rumo. Cinco. Cinco e a rota volta a ser rota.'],
    andamento:['Cinco. Eu conto pelos passos que param de vir do lado errado.'],
    entrega:['Cinco. A rota está silenciosa do jeito certo.',
             'Isto veio da última caravana que passou inteira. Faz doze anos.'],
    depois:['Passo por aqui de novo no mês que vem. Vivo, dessa vez.'],
    premio:{gold:6000, itens:['a_astral','rebirth']},
  },

};;

/* --- Curva de EXP --------------------------------------------------
   Calibrada para ~10-14 batalhas por nível no início. O EXP NÃO é
   dividido entre os membros (party de 5 tornaria a curva insuportável):
   cada sobrevivente recebe o total do encontro. */
const expToNext = lvl => Math.floor(28 * Math.pow(lvl, 1.5)) + 30 * lvl;

/* Fração do EXP que vai para quem ficou fora do grupo em campo. */
